/**
 * FEDIAF Nutrition Standards Seed Script
 * Seeds nutrition standards based on FEDIAF Nutritional Guidelines 2024
 * Used for recipe compliance checking
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * FEDIAF 2024 Nutrition Standards
 * Values are per 1000 kcal ME (Metabolizable Energy)
 * Basis: DM = Dry Matter, AF = As Fed
 *
 * References:
 * - FEDIAF Nutritional Guidelines for Complete and Complementary Pet Food for Cats and Dogs, 2024
 * - NRC Nutrient Requirements of Dogs and Cats, 2006
 */
const nutritionStandards = [
  // === 宏量营养素 (Macronutrients) ===
  {
    nutrientKey: 'protein',
    nutrientName: '蛋白质',
    nutrientNameEn: 'Protein',
    unit: 'g/1000kcal',
    category: 'MACRONUTRIENT',
    minValueAdult: 45.0,
    maxValueAdult: null,
    minValuePuppy: 56.3,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 1,
  },
  {
    nutrientKey: 'fat',
    nutrientName: '脂肪',
    nutrientNameEn: 'Fat',
    unit: 'g/1000kcal',
    category: 'MACRONUTRIENT',
    minValueAdult: 21.3,
    maxValueAdult: null,
    minValuePuppy: 33.8,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 2,
  },
  {
    nutrientKey: 'fiber',
    nutrientName: '纤维',
    nutrientNameEn: 'Fiber (Crude)',
    unit: '%',
    category: 'MACRONUTRIENT',
    minValueAdult: null,
    maxValueAdult: null,
    minValuePuppy: null,
    maxValuePuppy: null,
    basis: 'DM',
    notes: '无强制标准，建议不超过5%',
    sortOrder: 3,
  },
  {
    nutrientKey: 'ash',
    nutrientName: '灰分',
    nutrientNameEn: 'Ash',
    unit: '%',
    category: 'MACRONUTRIENT',
    minValueAdult: null,
    maxValueAdult: null,
    minValuePuppy: null,
    maxValuePuppy: null,
    basis: 'DM',
    notes: '无强制标准，建议不超过10%',
    sortOrder: 4,
  },
  {
    nutrientKey: 'moisture',
    nutrientName: '水分',
    nutrientNameEn: 'Moisture',
    unit: '%',
    category: 'MACRONUTRIENT',
    minValueAdult: null,
    maxValueAdult: null,
    minValuePuppy: null,
    maxValuePuppy: null,
    basis: 'AF',
    notes: '鲜食通常70-75%',
    sortOrder: 5,
  },
  {
    nutrientKey: 'carbohydrate',
    nutrientName: '碳水化合物',
    nutrientNameEn: 'Carbohydrate (NFE)',
    unit: '%',
    category: 'MACRONUTRIENT',
    minValueAdult: null,
    maxValueAdult: null,
    minValuePuppy: null,
    maxValuePuppy: null,
    basis: 'DM',
    notes: '无强制标准，鲜食通常较低',
    sortOrder: 6,
  },

  // === 矿物质 (Minerals) ===
  {
    nutrientKey: 'calcium',
    nutrientName: '钙',
    nutrientNameEn: 'Calcium',
    unit: 'g/1000kcal',
    category: 'MINERAL',
    minValueAdult: 0.5,
    maxValueAdult: 7.1,
    minValuePuppy: 1.25,
    maxValuePuppy: 5.0,
    basis: 'DM',
    sortOrder: 10,
  },
  {
    nutrientKey: 'phosphorus',
    nutrientName: '磷',
    nutrientNameEn: 'Phosphorus',
    unit: 'g/1000kcal',
    category: 'MINERAL',
    minValueAdult: 0.4,
    maxValueAdult: 5.0,
    minValuePuppy: 1.0,
    maxValuePuppy: 4.0,
    basis: 'DM',
    sortOrder: 11,
  },
  {
    nutrientKey: 'ca_p_ratio',
    nutrientName: '钙磷比',
    nutrientNameEn: 'Calcium:Phosphorus Ratio',
    unit: 'ratio',
    category: 'MINERAL',
    minValueAdult: 1.0,
    maxValueAdult: 2.0,
    minValuePuppy: 1.0,
    maxValuePuppy: 2.0,
    basis: 'DM',
    notes: '钙磷比应在1:1至2:1之间',
    sortOrder: 12,
  },
  {
    nutrientKey: 'potassium',
    nutrientName: '钾',
    nutrientNameEn: 'Potassium',
    unit: 'g/1000kcal',
    category: 'MINERAL',
    minValueAdult: 0.44,
    maxValueAdult: null,
    minValuePuppy: 0.44,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 13,
  },
  {
    nutrientKey: 'sodium',
    nutrientName: '钠',
    nutrientNameEn: 'Sodium',
    unit: 'g/1000kcal',
    category: 'MINERAL',
    minValueAdult: 0.08,
    maxValueAdult: 1.5,
    minValuePuppy: 0.25,
    maxValuePuppy: 1.5,
    basis: 'DM',
    sortOrder: 14,
  },
  {
    nutrientKey: 'magnesium',
    nutrientName: '镁',
    nutrientNameEn: 'Magnesium',
    unit: 'mg/1000kcal',
    category: 'MINERAL',
    minValueAdult: 54,
    maxValueAdult: 250,
    minValuePuppy: 54,
    maxValuePuppy: 250,
    basis: 'DM',
    sortOrder: 15,
  },
  {
    nutrientKey: 'iron',
    nutrientName: '铁',
    nutrientNameEn: 'Iron',
    unit: 'mg/1000kcal',
    category: 'MINERAL',
    minValueAdult: 5.0,
    maxValueAdult: 61.7,
    minValuePuppy: 11.0,
    maxValuePuppy: 61.7,
    basis: 'DM',
    sortOrder: 16,
  },
  {
    nutrientKey: 'zinc',
    nutrientName: '锌',
    nutrientNameEn: 'Zinc',
    unit: 'mg/1000kcal',
    category: 'MINERAL',
    minValueAdult: 9.6,
    maxValueAdult: 100,
    minValuePuppy: 25.0,
    maxValuePuppy: 100,
    basis: 'DM',
    sortOrder: 17,
  },
  {
    nutrientKey: 'copper',
    nutrientName: '铜',
    nutrientNameEn: 'Copper',
    unit: 'mg/1000kcal',
    category: 'MINERAL',
    minValueAdult: 1.0,
    maxValueAdult: 12.5,
    minValuePuppy: 2.0,
    maxValuePuppy: 12.5,
    basis: 'DM',
    sortOrder: 18,
  },
  {
    nutrientKey: 'manganese',
    nutrientName: '锰',
    nutrientNameEn: 'Manganese',
    unit: 'mg/1000kcal',
    category: 'MINERAL',
    minValueAdult: 0.77,
    maxValueAdult: 20,
    minValuePuppy: 0.77,
    maxValuePuppy: 20,
    basis: 'DM',
    sortOrder: 19,
  },
  {
    nutrientKey: 'iodine',
    nutrientName: '碘',
    nutrientNameEn: 'Iodine',
    unit: 'mcg/1000kcal',
    category: 'MINERAL',
    minValueAdult: 96,
    maxValueAdult: 2000,
    minValuePuppy: 193,
    maxValuePuppy: 2000,
    basis: 'DM',
    sortOrder: 20,
  },
  {
    nutrientKey: 'selenium',
    nutrientName: '硒',
    nutrientNameEn: 'Selenium',
    unit: 'mcg/1000kcal',
    category: 'MINERAL',
    minValueAdult: 19.3,
    maxValueAdult: 100,
    minValuePuppy: 38.5,
    maxValuePuppy: 100,
    basis: 'DM',
    sortOrder: 21,
  },

  // === 脂溶性维生素 (Fat-Soluble Vitamins) ===
  {
    nutrientKey: 'vitamin_a',
    nutrientName: '维生素A',
    nutrientNameEn: 'Vitamin A',
    unit: 'IU/1000kcal',
    category: 'VITAMIN_FAT_SOLUBLE',
    minValueAdult: 251,
    maxValueAdult: 25000,
    minValuePuppy: 502,
    maxValuePuppy: 25000,
    basis: 'DM',
    sortOrder: 30,
  },
  {
    nutrientKey: 'vitamin_d3',
    nutrientName: '维生素D3',
    nutrientNameEn: 'Vitamin D3',
    unit: 'IU/1000kcal',
    category: 'VITAMIN_FAT_SOLUBLE',
    minValueAdult: 54,
    maxValueAdult: 200,
    minValuePuppy: 54,
    maxValuePuppy: 200,
    basis: 'DM',
    sortOrder: 31,
  },
  {
    nutrientKey: 'vitamin_e',
    nutrientName: '维生素E',
    nutrientNameEn: 'Vitamin E',
    unit: 'IU/1000kcal',
    category: 'VITAMIN_FAT_SOLUBLE',
    minValueAdult: 3.9,
    maxValueAdult: 1000,
    minValuePuppy: 3.9,
    maxValuePuppy: 1000,
    basis: 'DM',
    notes: '高脂肪配方需要更高剂量',
    sortOrder: 32,
  },

  // === 水溶性维生素 (Water-Soluble Vitamins) ===
  {
    nutrientKey: 'vitamin_b1',
    nutrientName: '维生素B1 (硫胺素)',
    nutrientNameEn: 'Thiamine (B1)',
    unit: 'mg/1000kcal',
    category: 'VITAMIN_WATER_SOLUBLE',
    minValueAdult: 0.17,
    maxValueAdult: null,
    minValuePuppy: 0.17,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 40,
  },
  {
    nutrientKey: 'vitamin_b2',
    nutrientName: '维生素B2 (核黄素)',
    nutrientNameEn: 'Riboflavin (B2)',
    unit: 'mg/1000kcal',
    category: 'VITAMIN_WATER_SOLUBLE',
    minValueAdult: 0.27,
    maxValueAdult: null,
    minValuePuppy: 0.54,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 41,
  },
  {
    nutrientKey: 'vitamin_b3',
    nutrientName: '维生素B3 (烟酸)',
    nutrientNameEn: 'Niacin (B3)',
    unit: 'mg/1000kcal',
    category: 'VITAMIN_WATER_SOLUBLE',
    minValueAdult: 1.39,
    maxValueAdult: null,
    minValuePuppy: 2.78,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 42,
  },
  {
    nutrientKey: 'vitamin_b5',
    nutrientName: '维生素B5 (泛酸)',
    nutrientNameEn: 'Pantothenic Acid (B5)',
    unit: 'mg/1000kcal',
    category: 'VITAMIN_WATER_SOLUBLE',
    minValueAdult: 1.04,
    maxValueAdult: null,
    minValuePuppy: 2.08,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 43,
  },
  {
    nutrientKey: 'vitamin_b6',
    nutrientName: '维生素B6 (吡哆醇)',
    nutrientNameEn: 'Pyridoxine (B6)',
    unit: 'mg/1000kcal',
    category: 'VITAMIN_WATER_SOLUBLE',
    minValueAdult: 0.09,
    maxValueAdult: null,
    minValuePuppy: 0.18,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 44,
  },
  {
    nutrientKey: 'vitamin_b12',
    nutrientName: '维生素B12 (钴胺素)',
    nutrientNameEn: 'Cobalamin (B12)',
    unit: 'mcg/1000kcal',
    category: 'VITAMIN_WATER_SOLUBLE',
    minValueAdult: 2.5,
    maxValueAdult: null,
    minValuePuppy: 2.5,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 45,
  },
  {
    nutrientKey: 'folate',
    nutrientName: '叶酸',
    nutrientNameEn: 'Folate',
    unit: 'mcg/1000kcal',
    category: 'VITAMIN_WATER_SOLUBLE',
    minValueAdult: 27,
    maxValueAdult: null,
    minValuePuppy: 54,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 46,
  },
  {
    nutrientKey: 'choline',
    nutrientName: '胆碱',
    nutrientNameEn: 'Choline',
    unit: 'mg/1000kcal',
    category: 'VITAMIN_WATER_SOLUBLE',
    minValueAdult: 171,
    maxValueAdult: null,
    minValuePuppy: 342,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 47,
  },

  // === 必需氨基酸 (Essential Amino Acids) ===
  {
    nutrientKey: 'arginine',
    nutrientName: '精氨酸',
    nutrientNameEn: 'Arginine',
    unit: 'g/1000kcal',
    category: 'AMINO_ACID',
    minValueAdult: 0.27,
    maxValueAdult: null,
    minValuePuppy: 0.27,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 50,
  },
  {
    nutrientKey: 'histidine',
    nutrientName: '组氨酸',
    nutrientNameEn: 'Histidine',
    unit: 'g/1000kcal',
    category: 'AMINO_ACID',
    minValueAdult: 0.19,
    maxValueAdult: null,
    minValuePuppy: 0.21,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 51,
  },
  {
    nutrientKey: 'isoleucine',
    nutrientName: '异亮氨酸',
    nutrientNameEn: 'Isoleucine',
    unit: 'g/1000kcal',
    category: 'AMINO_ACID',
    minValueAdult: 0.33,
    maxValueAdult: null,
    minValuePuppy: 0.39,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 52,
  },
  {
    nutrientKey: 'leucine',
    nutrientName: '亮氨酸',
    nutrientNameEn: 'Leucine',
    unit: 'g/1000kcal',
    category: 'AMINO_ACID',
    minValueAdult: 0.58,
    maxValueAdult: null,
    minValuePuppy: 0.68,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 53,
  },
  {
    nutrientKey: 'lysine',
    nutrientName: '赖氨酸',
    nutrientNameEn: 'Lysine',
    unit: 'g/1000kcal',
    category: 'AMINO_ACID',
    minValueAdult: 0.33,
    maxValueAdult: null,
    minValuePuppy: 0.39,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 54,
  },
  {
    nutrientKey: 'methionine_cystine',
    nutrientName: '蛋氨酸+胱氨酸',
    nutrientNameEn: 'Methionine + Cystine',
    unit: 'g/1000kcal',
    category: 'AMINO_ACID',
    minValueAdult: 0.33,
    maxValueAdult: null,
    minValuePuppy: 0.39,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 55,
  },
  {
    nutrientKey: 'phenylalanine_tyrosine',
    nutrientName: '苯丙氨酸+酪氨酸',
    nutrientNameEn: 'Phenylalanine + Tyrosine',
    unit: 'g/1000kcal',
    category: 'AMINO_ACID',
    minValueAdult: 0.65,
    maxValueAdult: null,
    minValuePuppy: 0.77,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 56,
  },
  {
    nutrientKey: 'threonine',
    nutrientName: '苏氨酸',
    nutrientNameEn: 'Threonine',
    unit: 'g/1000kcal',
    category: 'AMINO_ACID',
    minValueAdult: 0.31,
    maxValueAdult: null,
    minValuePuppy: 0.36,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 57,
  },
  {
    nutrientKey: 'tryptophan',
    nutrientName: '色氨酸',
    nutrientNameEn: 'Tryptophan',
    unit: 'g/1000kcal',
    category: 'AMINO_ACID',
    minValueAdult: 0.1,
    maxValueAdult: null,
    minValuePuppy: 0.12,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 58,
  },
  {
    nutrientKey: 'valine',
    nutrientName: '缬氨酸',
    nutrientNameEn: 'Valine',
    unit: 'g/1000kcal',
    category: 'AMINO_ACID',
    minValueAdult: 0.42,
    maxValueAdult: null,
    minValuePuppy: 0.49,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 59,
  },

  // === 脂肪酸 (Fatty Acids) ===
  {
    nutrientKey: 'linoleic_acid',
    nutrientName: '亚油酸 (Omega-6)',
    nutrientNameEn: 'Linoleic Acid (Omega-6)',
    unit: 'g/1000kcal',
    category: 'FATTY_ACID',
    minValueAdult: 2.1,
    maxValueAdult: null,
    minValuePuppy: 3.3,
    maxValuePuppy: null,
    basis: 'DM',
    sortOrder: 60,
  },
  {
    nutrientKey: 'alpha_linolenic_acid',
    nutrientName: 'α-亚麻酸 (Omega-3)',
    nutrientNameEn: 'Alpha-Linolenic Acid (Omega-3)',
    unit: 'g/1000kcal',
    category: 'FATTY_ACID',
    minValueAdult: 0.04,
    maxValueAdult: null,
    minValuePuppy: 0.07,
    maxValuePuppy: null,
    basis: 'DM',
    notes: 'EPA+DHA可替代',
    sortOrder: 61,
  },
  {
    nutrientKey: 'epa_dha',
    nutrientName: 'EPA + DHA',
    nutrientNameEn: 'EPA + DHA',
    unit: 'g/1000kcal',
    category: 'FATTY_ACID',
    minValueAdult: 0.04,
    maxValueAdult: null,
    minValuePuppy: 0.07,
    maxValuePuppy: null,
    basis: 'DM',
    notes: '推荐值，非强制',
    sortOrder: 62,
  },

  // === 其他 (Other) ===
  {
    nutrientKey: 'taurine',
    nutrientName: '牛磺酸',
    nutrientNameEn: 'Taurine',
    unit: 'mg/1000kcal',
    category: 'OTHER',
    minValueAdult: null,
    maxValueAdult: null,
    minValuePuppy: null,
    maxValuePuppy: null,
    basis: 'DM',
    notes: '犬类可自身合成，非必需但推荐',
    sortOrder: 70,
  },
  {
    nutrientKey: 'energy_density',
    nutrientName: '能量密度',
    nutrientNameEn: 'Energy Density',
    unit: 'kcal/kg',
    category: 'OTHER',
    minValueAdult: 1200,
    maxValueAdult: 2000,
    minValuePuppy: 1500,
    maxValuePuppy: 2000,
    basis: 'AF',
    notes: '鲜食通常1400-1800 kcal/kg',
    sortOrder: 71,
  },
];

async function main() {
  console.log('🌱 Seeding FEDIAF nutrition standards...');

  // 清空现有数据
  await prisma.nutritionStandardFediaf.deleteMany({});
  console.log('  ✓ Cleared existing standards');

  // 插入新数据
  for (const standard of nutritionStandards) {
    await prisma.nutritionStandardFediaf.create({
      data: {
        nutrientKey: standard.nutrientKey,
        nutrientName: standard.nutrientName,
        nutrientNameEn: standard.nutrientNameEn,
        unit: standard.unit,
        category: standard.category,
        minValueAdult: standard.minValueAdult,
        maxValueAdult: standard.maxValueAdult,
        minValuePuppy: standard.minValuePuppy,
        maxValuePuppy: standard.maxValuePuppy,
        basis: standard.basis,
        notes: standard.notes,
        sortOrder: standard.sortOrder,
        isActive: true,
      },
    });
  }

  console.log(`  ✓ Inserted ${nutritionStandards.length} nutrition standards`);
  console.log('✅ FEDIAF nutrition standards seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding nutrition standards:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
