/**
 * Dog Breed Seed Script - 200 Unique Breeds
 * Complete breed database from AKC with AAHA standards
 * Sorted by China mainland commonness
 *
 * Data sources:
 * - AKC Breed Weight Chart (weight data)
 * - AAHA Guidelines (size/age standards)
 * - Chinese translations for breed names
 */

import { PrismaClient } from '@prisma/client';
import { mergeBreedAliases } from './breed-alias-catalog';

const prisma = new PrismaClient();

type SeedBreed = {
  name: string
  aliases?: string[]
  sizeCategory: 'SMALL' | 'MEDIUM' | 'LARGE' | 'GIANT'
  growthCurveType: 'STANDARD' | 'SLOW'
  adultAgeMonths: number
  seniorAgeYears: number
  averageAdultWeightKg: number
}

/**
 * Size classification based on AAHA standards:
 * - SMALL: < 10kg (adult: 10 months, senior: 11 years)
 * - MEDIUM: 10-25kg (adult: 12 months, senior: 10 years)
 * - LARGE: 25-45kg (adult: 18 months, senior: 8 years)
 * - GIANT: > 45kg (adult: 24 months, senior: 7 years)
 */
const dogBreeds: SeedBreed[] = [
  // ===========================
  // TOP 20 - Most Common in China
  // ===========================
  {
    name: '拉布拉多',
    aliases: ['拉拉', '拉布拉多犬'],
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 31.8,
  },
  {
    name: '泰迪',
    aliases: ['泰迪犬', '玩具贵宾犬', '贵宾犬'],
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 2.3,
  },
  {
    name: '贵宾犬(小型)',
    aliases: ['贵宾犬', '迷你贵宾犬', '泰迪', '迷你贵宾'],
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.8,
  },
  {
    name: '贵宾犬(标准)',
    aliases: ['贵宾犬', '标准贵宾犬', '大贵宾', '泰迪'],
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '金毛',
    aliases: ['金毛犬', '金毛巡回猎犬'],
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 29.5,
  },
  {
    name: '比熊',
    aliases: ['比熊犬', '比熊弗里兹犬'],
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 5.4,
  },
  {
    name: '哈士奇',
    aliases: ['西伯利亚哈士奇'],
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '德牧',
    aliases: ['德国牧羊犬', '德国黑背'],
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 34.0,
  },
  {
    name: '边牧',
    aliases: ['边境牧羊犬', '边境牧羊'],
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '柯基',
    aliases: ['威尔士柯基', '柯基犬'],
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 11.3,
  },
  {
    name: '萨摩耶',
    aliases: ['萨摩耶犬'],
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '法国斗牛犬',
    aliases: ['法斗', '法牛'],
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 11.3,
  },
  {
    name: '吉娃娃',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 1.8,
  },
  {
    name: '博美',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 2.3,
  },
  {
    name: '雪纳瑞(小型)',
    aliases: ['雪纳瑞', '小型雪纳瑞'],
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.8,
  },
  {
    name: '约克夏',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 3.2,
  },
  {
    name: '马尔济斯',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 3.2,
  },
  {
    name: '腊肠犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.1,
  },
  {
    name: '阿拉斯加',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 38.6,
  },
  {
    name: '杜宾',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 40.8,
  },

  // ===========================
  // POPULAR GUARD & WORKING BREEDS
  // ===========================
  {
    name: '罗威纳',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 50.0,
  },
  {
    name: '大白熊',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 52.2,
  },
  {
    name: '圣伯纳',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 65.8,
  },
  {
    name: '藏獒',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 63.5,
  },
  {
    name: '斗牛犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '拳师犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 29.5,
  },
  {
    name: '马士提夫',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 72.6,
  },
  {
    name: '卡斯罗',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 45.4,
  },
  {
    name: '高加索',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 70.3,
  },
  {
    name: '大丹犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 61.2,
  },

  // ===========================
  // TERRIERS (梗犬)
  // ===========================
  {
    name: '西高地',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.1,
  },
  {
    name: '牛头梗',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 25.0,
  },
  {
    name: '杰克罗素梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.4,
  },
  {
    name: '凯利蓝梗',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },
  {
    name: '苏格兰梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.5,
  },
  {
    name: '贝灵顿梗',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 9.1,
  },
  {
    name: '诺福克梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 5.4,
  },
  {
    name: '斯塔福郡斗牛梗',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 15.9,
  },
  {
    name: '美国斗牛梗',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 25.0,
  },
  {
    name: '湖畔梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 7.7,
  },
  {
    name: '万能梗',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },

  // ===========================
  // HERDING DOGS (牧羊犬)
  // ===========================
  {
    name: '喜乐蒂',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.1,
  },
  {
    name: '古代牧羊犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 31.8,
  },
  {
    name: '澳大利亚牧牛犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },
  {
    name: '澳洲牧羊犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 25.0,
  },
  {
    name: '卡迪根威尔士柯基',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 11.3,
  },
  {
    name: '比利时牧羊犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '比利时马利诺斯',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '长须柯利',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '边境梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.8,
  },
  {
    name: '比利时特弗伦犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 27.2,
  },

  // ===========================
  // SPORTING DOGS (运动犬)
  // ===========================
  {
    name: '可卡犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 13.6,
  },
  {
    name: '魏玛猎犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 31.8,
  },
  {
    name: '德国刚毛指示犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 29.5,
  },
  {
    name: '指示犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '英国激飞猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '爱尔兰塞特犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 29.5,
  },
  {
    name: '戈登塞特犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '布略塔尼犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 16.8,
  },
  {
    name: '美国水猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 13.6,
  },

  // ===========================
  // HOUNDS (猎犬)
  // ===========================
  {
    name: '阿富汗猎犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '巴塞特猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 25.0,
  },
  {
    name: '比格犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 11.3,
  },
  {
    name: '黑褐色猎浣熊犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 36.3,
  },
  {
    name: '寻血猎犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 45.4,
  },
  {
    name: '灵缇',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 31.8,
  },
  {
    name: '挪威猎麋犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '罗得西亚脊背犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 34.0,
  },
  {
    name: '萨路基猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '惠比特犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 13.6,
  },
  {
    name: '依比赞猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '法老王猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '苏格兰猎鹿犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 45.4,
  },
  {
    name: '美国猎狐犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '英国猎狐犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 31.8,
  },

  // ===========================
  // TOY BREEDS (小型玩赏犬)
  // ===========================
  {
    name: '北京犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 5.0,
  },
  {
    name: '布鲁塞尔格里芬犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 4.5,
  },
  {
    name: '蝴蝶犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 4.1,
  },
  {
    name: '日本尖嘴犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 3.6,
  },
  {
    name: '中国冠毛犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 4.5,
  },
  {
    name: '意大利灰狗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 3.6,
  },
  {
    name: '曼彻斯特梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 7.7,
  },
  {
    name: '迷你品',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 4.1,
  },
  {
    name: '丝毛梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 4.5,
  },

  // ===========================
  // NON-SPORTING DOGS (非运动犬)
  // ===========================
  {
    name: '松狮犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '沙皮犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '巴哥犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 8.2,
  },
  {
    name: '拉萨犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.4,
  },
  {
    name: '查理王小猎犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 8.2,
  },
  {
    name: '波士顿梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.8,
  },
  {
    name: '西施犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 5.0,
  },
  {
    name: '柴犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 9.1,
  },
  {
    name: '秋田犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 45.0,
  },
  {
    name: '荷兰毛狮犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },

  // ===========================
  // WORKING DOGS (工作犬)
  // ===========================
  {
    name: '伯恩山犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 45.0,
  },
  {
    name: '纽芬兰犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 68.0,
  },
  {
    name: '葡萄牙水犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '雪纳犬(标准)',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 15.9,
  },
  {
    name: '巨型雪纳瑞',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 34.0,
  },
  {
    name: '伯瑞犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 34.0,
  },
  {
    name: '坎高犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 63.5,
  },
  {
    name: '法兰德斯牧牛犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 40.8,
  },

  // ===========================
  // ADDITIONAL AKC BREEDS (补充的AKC品种)
  // ===========================
  {
    name: '切萨皮克湾寻回犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 34.0,
  },
  {
    name: '克伦伯猎鹬犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 13.6,
  },
  {
    name: '英国可卡犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 13.6,
  },
  {
    name: '田野猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '新斯科舍诱鸭寻回犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '德国短毛指示犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 31.8,
  },
  {
    name: '刚毛指示格里芬犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '爱尔兰水猎犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 29.5,
  },
  {
    name: '爱尔兰红白塞特犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '威尔士激飞猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },
  {
    name: '美国斗牛犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 40.8,
  },
  {
    name: '波索尔',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 38.6,
  },
  {
    name: '芬兰拉普猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '兰开斯顿赫勒犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '巴西菲勒犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 68.0,
  },
  {
    name: '阿根廷杜高犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 40.8,
  },
  {
    name: '中亚牧羊犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 65.8,
  },
  {
    name: '伯灵顿梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.8,
  },
  {
    name: '凯恩梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.4,
  },
  {
    name: '丹迪丁蒙梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.1,
  },
  {
    name: '福克斯梗(刚毛)',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 8.6,
  },
  {
    name: '福克斯梗(平滑)',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 8.2,
  },
  {
    name: '格罗恩戴尔犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '迷你斗牛梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 11.3,
  },
  {
    name: '罗威士梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 5.9,
  },
  {
    name: '斯凯梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.5,
  },
  {
    name: '威尔士梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.1,
  },
  {
    name: '澳大利亚梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.8,
  },
  {
    name: '美国斯塔福郡梗',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '比利时拉坎诺斯犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },
  {
    name: '荷兰牧羊犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '芬兰尖嘴犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 7.7,
  },
  {
    name: '波密犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 2.3,
  },
  {
    name: '瑞典猎鹿犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '卡斯提犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '阿彭策尔山地犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '瑞士卷毛犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '恩特雷布赫山地犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '大瑞士山地犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 50.0,
  },
  {
    name: '白色瑞士牧羊犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 34.0,
  },
  {
    name: '库瓦斯犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 63.5,
  },
  {
    name: '马雷马犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 61.2,
  },
  {
    name: '皮卡迪牧羊犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 7.3,
  },
  {
    name: '波兰低地牧羊犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },
  {
    name: '贝里牧羊犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 8.2,
  },
  {
    name: '谢德兰牧羊犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.1,
  },
  {
    name: '可蒙犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 59.0,
  },
  {
    name: '万达犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 45.0,
  },
  {
    name: '阿扎瓦克犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '巴仙吉犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 10.9,
  },
  {
    name: '刚果犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.5,
  },
  {
    name: '细犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 31.8,
  },
  {
    name: '蒙古猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '那不勒斯獒犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 61.2,
  },
  {
    name: '法国狼犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 63.5,
  },
  {
    name: '美国爱斯基摩犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 15.9,
  },
  {
    name: '卡斯罗犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 45.4,
  },
  {
    name: '西班牙加纳利犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 50.0,
  },
  {
    name: '斯洛伐克牧羊犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 29.5,
  },
  {
    name: '图利犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '黑棕梗',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '巴塞特格里芬旺代犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 14.1,
  },
  {
    name: '大旺代格里芬犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 38.6,
  },
  {
    name: '奥弗涅梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.5,
  },
  {
    name: '比利牛斯梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 11.3,
  },
  {
    name: '圣于斯犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.5,
  },
  {
    name: '波米特',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 3.2,
  },
  {
    name: '巴比松犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 38.6,
  },
  {
    name: '波尔多犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 68.0,
  },
  {
    name: '布洛泰梗',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },
  {
    name: '中亚牧羊犬(前苏联)',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 65.8,
  },
  {
    name: '莫斯科看护犬',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 70.3,
  },
  {
    name: '俄国黑梗',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 45.0,
  },
  {
    name: '西班牙獒',
    sizeCategory: 'GIANT',
    growthCurveType: 'SLOW',
    adultAgeMonths: 24,
    seniorAgeYears: 7,
    averageAdultWeightKg: 72.6,
  },
  {
    name: '泰国班吉犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },
  {
    name: '越南脊背犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },
  // ===========================
  // FINAL BREEDS TO REACH 200
  // ===========================
  {
    name: '美国猎浣熊犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 36.3,
  },
  {
    name: '英国雪达犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 31.8,
  },
  {
    name: '戈登雪达犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 29.5,
  },
  {
    name: '爱尔兰雪达犬',
    sizeCategory: 'LARGE',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 18,
    seniorAgeYears: 8,
    averageAdultWeightKg: 27.2,
  },
  {
    name: '日本梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 4.5,
  },
  {
    name: '捷克梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.8,
  },
  {
    name: '杰克罗素小梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 5.9,
  },
  {
    name: '玩具曼彻斯特梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 3.2,
  },
  {
    name: '诺维奇梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 5.4,
  },
  {
    name: '帕森罗素梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 7.3,
  },
  {
    name: '美国可卡犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 13.6,
  },
  {
    name: '兰开斯特激飞猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },
  {
    name: '俄罗斯玩具犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 2.7,
  },
  {
    name: '提洛尔梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 4.1,
  },
  {
    name: '玩具美国爱斯基摩犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 4.5,
  },
  {
    name: '小型澳洲牧羊犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 9.1,
  },
  {
    name: '圣日耳曼犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 22.7,
  },
  {
    name: '斯洛伐克梗',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 7.7,
  },
  {
    name: '瑞典拉普猎犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 18.1,
  },
  {
    name: '挪威布哈德犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
  {
    name: '荷兰斯马斯犬',
    sizeCategory: 'SMALL',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 10,
    seniorAgeYears: 11,
    averageAdultWeightKg: 6.4,
  },
  {
    name: '克罗地亚牧羊犬',
    sizeCategory: 'MEDIUM',
    growthCurveType: 'STANDARD',
    adultAgeMonths: 12,
    seniorAgeYears: 10,
    averageAdultWeightKg: 20.4,
  },
];

async function main() {
  console.log('🌱 Seeding 200 dog breeds...');

  for (const breed of dogBreeds) {
    // Check if breed already exists
    const existing = await prisma.dogBreed.findFirst({
      where: { name: breed.name },
    });

    if (existing) {
      console.log(`⏭️  Skipping ${breed.name} (already exists)`);
      continue;
    }

    const created = await prisma.dogBreed.create({
      data: {
        name: breed.name,
        aliases: mergeBreedAliases(breed.name, breed.aliases ?? []),
        sizeCategory: breed.sizeCategory as any,
        growthCurveType: breed.growthCurveType as any,
        adultAgeMonths: breed.adultAgeMonths,
        seniorAgeYears: breed.seniorAgeYears,
        averageAdultWeightKg: breed.averageAdultWeightKg,
      },
    });

    console.log(`✅ Created breed: ${created.name} (${created.id})`);
  }

  console.log('✨ 200 breed seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
