import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

const root = resolve(import.meta.dirname, '../..')
const read = (relativePath) => readFileSync(resolve(root, relativePath), 'utf8')

test('nutrition governance types expose Agent review and hard-gate fields', () => {
  const types = read('admin-web/src/types/nutritionGovernance.ts')

  assert.match(types, /NutritionCandidateAgentReview/)
  assert.match(types, /CandidateHardGateResults/)
  assert.match(types, /reviewGroup\?:/)
  assert.match(types, /ediblePortionLabel\?:/)
})

test('nutrition governance API exposes Agent review and batch confirmation', () => {
  const api = read('admin-web/src/api/nutritionGovernance.ts')

  assert.match(api, /reviewCandidateWithAgent/)
  assert.match(api, /batchConfirmCandidates/)
  assert.match(api, /applyIngredientCandidateConfiguration/)
  assert.match(api, /ConfirmNutritionCandidatePayload/)
})

test('nutrition governance workbench shows review queue controls and unified review drawer', () => {
  const page = read('admin-web/src/views/NutritionGovernance/index.vue')
  const table = read('admin-web/src/views/NutritionGovernance/components/FoodCandidatesTable.vue')
  const drawer = read('admin-web/src/views/NutritionGovernance/components/IngredientNutritionWorkbenchDrawer.vue')
  const preview = read('admin-web/src/views/NutritionGovernance/components/NutritionProfilePreview.vue')

  assert.match(page, /reviewGroupFilter/)
  assert.match(page, /candidateKeywordFilter/)
  assert.match(page, /visibleCandidates/)
  assert.match(page, /搜索原料\/候选词条/)
  assert.match(page, /handleBatchConfirm/)
  assert.doesNotMatch(page, /CandidateReviewDrawer/)
  assert.match(page, /@confirm="handleOpenIngredientWorkbench"/)
  assert.match(table, /ingredientRows/)
  assert.match(table, /候选数/)
  assert.match(table, /Agent建议/)
  assert.match(table, /agentReviewDetailText/)
  assert.match(table, /语义分析/)
  assert.match(table, /硬闸门/)
  assert.match(drawer, /营养状态/)
  assert.match(drawer, /NUTRITION_PREPARATION_STATE_OPTIONS/)
  assert.match(drawer, /NUTRITION_EDIBLE_PORTION_OPTIONS/)
  assert.match(drawer, /NUTRITION_PROCESSING_OPTIONS/)
  assert.match(drawer, /<el-select[\s\S]*v-model="row\.reviewForm\.preparationState"/)
  assert.doesNotMatch(drawer, /<el-input v-model="row\.reviewForm\.preparationStateLabel"/)
  assert.match(drawer, /主档案/)
  assert.match(drawer, /次级档案/)
  assert.match(preview, /INGREDIENT_NUTRITION_TAB_DEFINITIONS/)
  assert.match(preview, /nutrientGroups/)
  assert.match(preview, /sourceSummary/)
  assert.match(preview, /来源项：/)
  assert.match(preview, /conversionNotes/)
  assert.match(preview, /MG_PER_G/)
  assert.match(preview, /IU_PER_UG/)
  assert.match(preview, /reviewOnlyCustomItems/)
  assert.match(preview, /reviewCategoryLabel/)
  assert.match(preview, /未计入主字段/)
  assert.match(preview, /toFixed\(3\)/)
  assert.match(preview, /已填/)
})

test('nutrition governance groups candidates by ingredient and supports primary and secondary review', () => {
  const page = read('admin-web/src/views/NutritionGovernance/index.vue')
  const table = read('admin-web/src/views/NutritionGovernance/components/FoodCandidatesTable.vue')
  const drawer = read('admin-web/src/views/NutritionGovernance/components/IngredientNutritionWorkbenchDrawer.vue')
  const types = read('admin-web/src/types/nutritionGovernance.ts')

  assert.match(types, /ApplyIngredientCandidateConfigurationPayload/)
  assert.match(page, /IngredientNutritionWorkbenchDrawer/)
  assert.match(page, /handleOpenIngredientWorkbench/)
  assert.match(page, /handleSaveIngredientWorkbench/)
  assert.doesNotMatch(table, /review-ingredient/)
  assert.doesNotMatch(table, /原料审核/)
  assert.match(table, /buildIngredientRows/)
  assert.match(table, /candidateCount/)
  assert.match(drawer, /原料营养档案审批/)
  assert.match(drawer, /selectedPrimaryCandidateId/)
  assert.match(drawer, /secondaryCandidateIds/)
  assert.match(drawer, /保存原料配置/)
})

test('ingredient review drawer can remap confirmed primary and secondary profiles', () => {
  const drawer = read('admin-web/src/views/NutritionGovernance/components/IngredientNutritionWorkbenchDrawer.vue')

  assert.match(drawer, /调整主\/次档案/)
  assert.match(drawer, /remappingConfirmedProfiles/)
  assert.match(drawer, /canEditCandidateMapping/)
  assert.match(drawer, /candidateMappingRole/)
  assert.match(drawer, /已确认档案可调整主次/)
  assert.match(drawer, /保存主\/次档案/)
  assert.match(drawer, /confirmationSnapshot/)
})

test('ingredient review drawer supports rematching wrong candidate sources', () => {
  const page = read('admin-web/src/views/NutritionGovernance/index.vue')
  const drawer = read('admin-web/src/views/NutritionGovernance/components/IngredientNutritionWorkbenchDrawer.vue')

  assert.match(drawer, /查找候选并排序/)
  assert.match(drawer, /USDA FDC ID/)
  assert.match(drawer, /导入候选/)
  assert.match(drawer, /reject-candidate/)
  assert.match(drawer, /import-usda/)
  assert.match(drawer, /flowers\|flower\|blossom/)
  assert.match(page, /handleRematchIngredientCandidates/)
  assert.match(page, /handleImportUsdaCandidateFromWorkbench/)
  assert.match(page, /handleRejectCandidateFromWorkbench/)
})

test('ingredient review drawer supports Agent ranking requirements and nutrition validation', () => {
  const page = read('admin-web/src/views/NutritionGovernance/index.vue')
  const api = read('admin-web/src/api/nutritionGovernance.ts')
  const types = read('admin-web/src/types/nutritionGovernance.ts')
  const drawer = read('admin-web/src/views/NutritionGovernance/components/IngredientNutritionWorkbenchDrawer.vue')

  assert.match(types, /RankFoodCandidatesWithAgentPayload/)
  assert.match(types, /onlineWhitelistSearch\?: boolean/)
  assert.match(types, /reviewModel\?: string/)
  assert.match(types, /CandidateNutritionValidationWithAgentResult/)
  assert.match(api, /rankFoodCandidatesWithAgent/)
  assert.match(api, /validateCandidateNutritionWithAgent/)
  assert.match(api, /rank-with-agent'[\s\S]*timeout:\s*180000/)
  assert.match(api, /nutrition-validation`[\s\S]*timeout:\s*180000/)
  assert.match(drawer, /匹配要求/)
  assert.match(drawer, /Agent 会先生成搜索词/)
  assert.match(drawer, /联网白名单搜索/)
  assert.match(drawer, /可信网页来源/)
  assert.match(drawer, /onlineWhitelistSearch/)
  assert.match(drawer, /推荐候选/)
  assert.match(drawer, /可作为备用或需复核/)
  assert.match(drawer, /不推荐但保留查看/)
  assert.match(drawer, /校验营养/)
  assert.match(drawer, /营养校验/)
  assert.match(drawer, /validationDetailItems/)
  assert.match(drawer, /缺失字段/)
  assert.match(drawer, /agentReviewDetailText/)
  assert.match(drawer, /语义分析/)
  assert.doesNotMatch(drawer, /-webkit-line-clamp:\s*2/)
  assert.match(drawer, /档案状态/)
  assert.match(drawer, /isEditableCandidate/)
  assert.match(drawer, /已确认/)
  assert.match(page, /handleRankIngredientCandidatesWithAgent/)
  assert.match(page, /handleValidateCandidateNutrition/)
  assert.match(page, /candidateNutritionValidationResults/)
})

test('ingredient review drawer separates Agent draft candidates from confirmed and excluded rows', () => {
  const drawer = read('admin-web/src/views/NutritionGovernance/components/IngredientNutritionWorkbenchDrawer.vue')
  const dialog = read('admin-web/src/views/Ingredients/components/IngredientNutritionDialog.vue')

  assert.match(drawer, /mode\?: 'GOVERNANCE' \| 'PROFILE_DRAFT'/)
  assert.match(drawer, /existingProfileSourceKeys\?: string\[\]/)
  assert.match(drawer, /const isProfileDraftMode = computed/)
  assert.match(drawer, /existingProfileSourceKeySet/)
  assert.match(drawer, /可入库候选/)
  assert.match(drawer, /已入库档案/)
  assert.match(drawer, /排除结果/)
  assert.match(drawer, /admissionCandidateRows/)
  assert.match(drawer, /confirmedCandidateRows/)
  assert.match(drawer, /excludedCandidateRows/)
  assert.match(drawer, /showExcludedCandidates/)
  assert.match(drawer, /本次仅搜索本地 USDA \/ NZFCD \/ CFCT/)
  assert.match(drawer, /未找到可入库营养档案/)
  assert.match(drawer, /isAdmissionCandidate/)
  assert.match(drawer, /isExcludedCandidate/)
  assert.match(drawer, /isExistingProfileCandidate/)
  assert.match(drawer, /isProfileDraftMode\.value && isAdmissionCandidate/)
  assert.match(drawer, /!isProfileDraftMode\.value &&/)
  assert.match(dialog, /mappedNutritionSourceKeys/)
  assert.match(dialog, /mode="PROFILE_DRAFT"/)
  assert.match(dialog, /:existing-profile-source-keys="mappedNutritionSourceKeys"/)
})
