export enum AiRecipeResultStatus {
  REVIEWABLE = 'REVIEWABLE',
  NEEDS_MANUAL_REVIEW = 'NEEDS_MANUAL_REVIEW',
  LIMITED_DRAFT = 'LIMITED_DRAFT',
  UNABLE_TO_COMPLETE = 'UNABLE_TO_COMPLETE',
}

export enum EvidenceLevel {
  A_CONFIRMED_DIAGNOSIS = 'A_CONFIRMED_DIAGNOSIS',
  B_TEST_INDICATED = 'B_TEST_INDICATED',
  C_OWNER_REPORTED = 'C_OWNER_REPORTED',
  D_ATTACHMENT_OBSERVATION = 'D_ATTACHMENT_OBSERVATION',
}

export enum MissingInfoCode {
  TARGET_WEIGHT = 'TARGET_WEIGHT',
  DIET_HISTORY = 'DIET_HISTORY',
  TREAT_INTAKE = 'TREAT_INTAKE',
  CONFIRMED_REPORT = 'CONFIRMED_REPORT',
  MCS_SCORE = 'MCS_SCORE',
}
